export const HUSKY: 'husky' = 'husky'
export const PRETTIER: 'prettier' = 'prettier'
export const TS: 'typescript' = 'typescript'
export const ESLINT: 'eslint' = 'eslint'
export const COMMITLINT: 'commitlint' = 'commitlint'
